### ISSUE TITLE
Insulation cleanup (OVERVIEW TICKET)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1534]
## Background

This ticket lists and references the issues that need to be closed in order to complete the cleanup of insulation modeling and implementation of the households and buildings sector.
### Research
- [x] Employment numbers for insulation are needed as a function of R-value (https://github.com/quintel/etsource/issues/351)
- [x] Buildings: Insulation costs need to be revised (https://github.com/quintel/etsource/issues/352)
- [x] Buildings: What to do with ventilation? (https://github.com/quintel/etsource/issues/353)
### Modeling
- [x] How to model employment figures for insulation? (https://github.com/quintel/etsource/issues/354)
- [x] Remove re-circulation and heat recovery converters (https://github.com/quintel/etsource/issues/355)
- [x] Climate slider should not influence the cost of insulation (https://github.com/quintel/etmodel/issues/1502)
- [x] Fix Employment queries. (https://github.com/quintel/etsource/issues/447)
- [x] Correct ETFlex score for insulation (https://github.com/quintel/mechanical_turk/issues/44)
### Front end
- [x] Adjust texts for insulation (1991 is now the difference between old and new houses), limits etc. (https://github.com/quintel/etmodel/issues/1539)
### Documentation
- [x] Upload used documents for insulation to refmanager (https://github.com/quintel/refman/issues/27)
