### ISSUE TITLE
Overview: space heating and hot water merge project

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#1595]
See https://github.com/quintel/inputexcel/issues/208 for the original overview ticket.

This is an overview for the space heating and hot water merge project. More info can be found in the [20130902_heating_hot_water_merge](https://www.dropbox.com/sh/unye17fa1z3ikwn/Dg0gt8_M1g) folder on Dropbox.

The way the space heating and hot water sections of the households sector are currently modelled in the ETM is not very intuitive because the user has to set the share of some technologies twice as they provide both space heating and hot water. These technologies are called 'combi' technologies for convenience. In addition, the graph is not very clean for this part of the households sector and, most importantly, the number of combi units are counted twice which requires a not so nice fix for the costs.

The goal of this project is to re-model the space heating and hot water sections. This issue contains a top level checklist of all actions required to reach this goal.

**Modelling**
5 days
- [ ] Create input statements
- [ ] Update input statements
- [ ] Remove input statements
- [ ] Update charts
- [ ] Update graph
- [ ] Update gqueries

**Interface**
3 days
- [ ] Add new slide for combi technology
- [ ] Update text with sliders
- [ ] Update etflex
- [ ] Update mixers

**Scenario's**
1 day
- [ ] Update preset scenario's
- [ ] Update database scenario's

**Testing**
1 day
- [ ] Update Mechanical Turk tests
- [ ] Test etmodel, etflex and mixer(s)

**Documentation**
1 day
- [ ] Write entry in Wiki
- [ ] Maintain and discuss tickets on Github
- [ ] Keep track of time registration
- [ ] Write documentation

**Communication, overhead and unforeseen**
2 days

**Sub-issues**

_ETModel_
- [ ] quintel/etmodel#1596
- [ ] quintel/etmodel#1597
- [ ] quintel/etmodel#1598
- [ ] quintel/etmodel#1605

_ETEngine_
- [ ] https://github.com/quintel/etengine/issues/603

_ETSource_
- [ ] https://github.com/quintel/etsource/issues/507
- [ ] https://github.com/quintel/etsource/issues/509
- [ ] https://github.com/quintel/etsource/issues/510
- [ ] https://github.com/quintel/etsource/issues/511
- [ ] https://github.com/quintel/etsource/issues/512
