### ISSUE TITLE
Wartsilla plant needs to be added

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1785]
This is includes:
- [x] Adding it to converter groups
- [x] Adding it to charts and table
- [x] Adding it to query groups (https://github.com/quintel/etsource/issues/789)
- [x] Adding it to dataset (https://github.com/quintel/etdataset/issues/439)
- [x] Adding slider (https://github.com/quintel/etmodel/issues/1784)
- [x] Adding update statement
- [x] Adding Mechanical Turk tests (https://github.com/quintel/mechanical_turk/issues/61)
- [x] Adding text (https://github.com/quintel/etmodel/issues/1791)
