### ISSUE TITLE
OVERVIEW TICKET "Storage"

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1868]
This ticket serves as the top-level description of the tasks/issues related to implementing 'Storage' in the ETM (as part of the "Alliander testing ground project").

# Research

- [x] Technical specs of P2P (batteries) need to be researched (https://github.com/quintel/etdataset/issues/596)
- [x] Technical specs of P2P (EV) need to be researched (https://github.com/quintel/etdataset/issues/597)
- [x] Technical specs of P2G need to be researched (https://github.com/quintel/etdataset/issues/598)
- [x] Technical specs of P2H need to be researched (https://github.com/quintel/etdataset/issues/599)
- [x] Demand profile for P2H need to be researched
- [x] Availability profile for P2P (EV) need to be researched

# ETMoses

- [x] individual batteries and EV need to be able to charge/discharge based on excess (local or global)
- [x] individual P2H and P2G installations need to convert electricity based on excess (local or global)
- [x] EVs should be able to deal with 'availability curves'

The tickets below are of lower priority but will be relevant in the later (demand-shifting/market models/business cases steps):
- [x] The current 'price' in the Merit Order should be known at every hour

~~individual batteries and EV need to be able to charge/discharge based on electricity price~~
~~individual P2H and P2G installations need to convert electricity based on electricity price~~
- [x] A demand profile for P2H needs to be added to the dataset

# Merit

- [x] P2P in batteries should become a participant (https://github.com/quintel/merit/issues/128)
- [x] P2P in EV should become a participant (https://github.com/quintel/merit/issues/129)
- [x] P2G should become a participant (https://github.com/quintel/merit/issues/130)
- [x] P2H should become a participant (https://github.com/quintel/merit/issues/132)
- [x] Import & export should become participants (https://github.com/quintel/merit/issues/133)
- [x] Curtailment should become a participant (kind of) (https://github.com/quintel/merit/issues/134)
- [x] Results of storage/conversion need to be communicated to the graph (https://github.com/quintel/merit/issues/135)
- [x] The demand profile for P2H needs to be scaled by the demand for hot water in households (https://github.com/quintel/merit/issues/131)

# ETM Front-end

- [x] A slider for P2P (batteries) should be included in the front-end
- [x] A slider/two sliders for P2G should be included in the front-end
- [x] The slider text for the electric water heater should be updated
- [x] A graph showing the 'uses' of excess electricity should be included in the front-end
- [x] A table showing installed capacities and volumes of P2P, P2H and P2G should be included in the front-end
- [ ] A "yes/no"-switch for constraining the interconnection capacity needs to be added to the front-end
- [x] A slider for physical import/export interconnectivity needs to be added to the front-end (https://github.com/quintel/etmodel/issues/1967)
- [x] A slider for availability of interconnectivity for export needs to be added to the front-end (https://github.com/quintel/etmodel/issues/1968)
- [x] A slider for availability of interconnectivity for import needs to be added to the front-end (https://github.com/quintel/etmodel/issues/1969)
- [x] Sliders for costs of P2P (batteries), P2H and P2G should be added to the front-end
- [x] A slider quantifying the availability of EV for P2P should be added to front-end
- [x] A slider quantifying the percentage of the available EV storage volume reserved for P2P should be added to front-end
- [x] An 'ordering' of storage options needs to added to the front-end (https://github.com/quintel/etmodel/issues/1965)
- [x] How do we show the user the amount of hydrogen which is mixed into the gas network? (https://github.com/quintel/etmodel/issues/1966)

# ETM Back-end

- [x] P2P nodes need to be added that store the total electricity stored in a year (for the chart)
- [x] P2G nodes need to be added that store the total gas produced from excess electricity
- [x] A P2H node may need to be included to keep track of the heat from excess electricity
- [x] Import and export need to be (optionally) constrained by sliders
- [x]  Data from P2H and P2G from Merit needs to be taken into account in future graph (https://github.com/quintel/etengine/issues/806)
- [x] Should we add a curtailment node to the graph? (https://github.com/quintel/etmodel/issues/1970)

**Comment by ChaelKruip** [comment]
Including @antw @jorisberkhout

**Comment by jorisberkhout** [comment]
I have modelled the availability of EV for storage based on typical trip data and made the results available on [Dropbox](https://www.dropbox.com/sh/i35c6bpe4b8xre1/AABV6l9bC65AjNs0g-IcSYmta?dl=0).

Including @ChaelKruip and @antw.

**Comment by jorisberkhout** [comment]
Changing milestone to 'Deploy February 2016'.

**Comment by ChaelKruip** [comment]
Assigning to @jorisberkhout

**Comment by jorisberkhout** [comment]
Closing this as most item have been implemented. Any remaining actionable items are logged in separate issues.
