### ISSUE TITLE
[Overview issue] Improved network calculation

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#1961]
**Background**

This issue describes a long anticipated improvement of the network calculation in the ETM. The network calculation is used to determine the additional network capacity that is required to facilitate the electrical technologies installed by the user and the associated costs.

**Current implementation**

In the current implementation of the network calculation, we compare the additional peak load (i.e. the difference in load between the future and present year for a scenario) to the available capacity of the network. Only if your additional peak load exceeds the available capacity, additional network capacity is required. The above calculation is performed for four relevant times in the year (winter day, winter evening, summer day and summer evening); these different times will yield different results because the additional peak load depends on the simultaneousness parameter of the electric technologies (i.e. the `simult_wd`, `simult_we`, `simult_sd` and `simult_se` attributes of the relevant nodes), e.g. a electric heat pump will put more load on the network during a winter evening than during a summer day. An identical calculation is performed for five of the six voltage levels in the ETM (LV, MV-LV transformers, MV-d, MV-t and HV-MV transformers), which differ because different technologies are connected to different voltage levels. All of the above is implemented in Gqueries.

The current implementation is an oversimplification of reality as it implies that you can first 'fill' all your available capacity before you have to start building additional capacity. In reality, however, each voltage level consist of several (or many) individual subnets, and the available capacity will be distributed unequally between them; some of the subnets will have more available capacity and some will have less available capacity. If the additional peak load on the network increases, you will most likely have to increase the capacity of the latter subnets to accommodate , while the former subnets are still fine.

**Proposed implementation**

In order to make the behaviour of the network calculation more realistic, we would like to implement distributions of the available capacity for the subnets in each of the voltage levels. In order to achieve this, the following changes have to be made to the model:

- [x] create new method to calculate the required additional network capacity based on distributions of the available capacity (https://github.com/quintel/etengine/issues/803)
- [x] rewrite Gqueries to use this new method (https://github.com/quintel/etsource/issues/1005)
- [x] write documentation (https://github.com/quintel/etdataset/issues/19)
- [ ] clean up the Gqueries (https://github.com/quintel/etsource/issues/1014)
- [x] have the results validated

**Results**

I have modeled the proposed implementation in Python to get a feel for the difference between the current and proposed implementation. Below are the results for one of the relevant voltage levels (LV voltage level). The most noticeable difference between the two is the much smoother behaviour of the proposed implementation, making the results of the network calculation much more realistic. In absolute terms, the difference between the current and proposed method is ~ 4 BLN EUR for all voltage levels combined.

![figure_1](https://cloud.githubusercontent.com/assets/4669028/11711255/5f999930-9f25-11e5-85d0-3e29c6e36fc3.png)

**Comment by jorisberkhout** [comment]
I have asked Alliander to validate the results of the new network calculation. Should any changes be required from this, I will open a separate issue. Cleaning up the Gqueries already has a separate issue. 

That seems to be all regarding the network calculation. Closing this issue.
